### ISSUE TITLE
preprocessor example

### ISSUE THREAD

**Issue by nawroth** [asciidoctor/asciidoctorj-groovy-dsl#4]
To do anything interesting with a preprocessor, it seems one has to return a new Reader instance, as the old one will be empty once the lines are read.
My question is: how to create a new Reader?

An example preprocessor which replaces some content would be very useful!

**Comment by robertpanzer** [comment]
Hi Anders,

you might want to take a look at this issue:
https://github.com/asciidoctor/asciidoctorj/issues/383
So in fact atm it only makes sense to modify the given preprocessor.

Am Mittwoch, 2. Dezember 2015 schrieb Anders Nawroth :

**Comment by nawroth** [comment]
Hi Robert!

I can't find any useful ways to modify it, like `replace_line` on the Ruby side.
Or am I missing something here?

**Comment by robertpanzer** [comment]
Well, we added the missing methods on the 1.6.0 branch: https://github.com/asciidoctor/asciidoctorj/blob/asciidoctorj-1.6.0/asciidoctorj-core/src/main/java/org/asciidoctor/extension/Reader.java

There you can get the lines and restore them again. 

But I did not try out yet if the current asciidoctorj-groovy-dislike works with the 1.6.0 snapshots.

**Comment by nawroth** [comment]
I tried it out and get

```
java.lang.NoClassDefFoundError: org/asciidoctor/ast/DocumentRuby
    at org.asciidoctor.groovydsl.AsciidoctorExtensionHandler.preprocessor(AsciidoctorExtensionHandler.groovy:84)
```

The new Reader looks good though!

**Comment by robertpanzer** [comment]
Oh yes, this is due to the renaming of the AST classes we have done on the 1.6.0 branch.
